Squashed commit of the following:
commit 2817fc8ce4ac2648cf072938c5ce5ad96d484365
Author: tttttangTH <tangtonghui0614@gmail.com>
Date:   Sun Nov 8 22:27:43 2020 -0500

    change function name 'SetCallback' as 'SetHasCallback'

commit 3c967931a271fa77f5f9892423b5a7f1854ceb2a
Author: kangping <wgtdkp@google.com>
Date:   Thu Oct 22 13:59:17 2020 +0800

    resolve conflicts with the master branch

commit 238f1c4c9a7363526dd18e25276f227e94d88b70
Author: kangping <wgtdkp@google.com>
Date:   Wed Oct 14 11:57:16 2020 +0800

    [rest] remove unused nginx config file

commit 340e1268c393e989b26af4cbba07d18ccfe9d9d4
Author: kangping <wgtdkp@google.com>
Date:   Wed Oct 14 11:36:00 2020 +0800

    [rest] refine code style

commit 2c939f8af65ab582ffe4f5070b6b3d184c21236a
Author: kangping <wgtdkp@google.com>
Date:   Wed Oct 14 11:33:14 2020 +0800

    [scripts] refine scripts setting up OTBR web with Nginx

commit 89bd0dfe04d0614f17c8cae1e24d385d59780add
Author: kangping <wgtdkp@google.com>
Date:   Wed Oct 14 11:14:13 2020 +0800

    [cmake] fix cmake installing frontend scripts

commit 0102d1400c327dc5628e1b89646d9568003e7d78
Author: kangping <wgtdkp@google.com>
Date:   Wed Oct 14 11:00:21 2020 +0800

    [3rd-party] remove simple web server

commit db7670bea84708f81cb2880546ea505f70bff318
Author: tttttangTH <tangtonghui0614@gmail.com>
Date:   Tue Oct 13 09:02:06 2020 -0400

    replace otbr-web

diff --git a/script/_nginx_config_install b/script/_nginx_config_install
--- a/script/_nginx_config_install
+++ b/script/_nginx_config_install
@@ -1,3 +1,4 @@
+#!/bin/bash
 #
 #  Copyright (c) 2020, The OpenThread Authors.
 #  All rights reserved.
@@ -26,13 +27,22 @@
 #  POSSIBILITY OF SUCH DAMAGE.
 #
 
-add_subdirectory(openthread EXCLUDE_FROM_ALL)
+readonly NGINX_CONF_DIR=/etc/nginx
 
-if(OTBR_REST)
-    add_subdirectory(angular)
-    add_subdirectory(angular-material)
-    add_subdirectory(d3js)
-    add_subdirectory(cJSON EXCLUDE_FROM_ALL)
-    add_subdirectory(http-parser EXCLUDE_FROM_ALL)
-    add_subdirectory(mdl)
-endif()
+nginx_config_install()
+{
+    if command -v nginx; then
+        sudo cp etc/rest/otbr-nginx.conf "${NGINX_CONF_DIR}"/sites-available/
+        sudo rm -rf "${NGINX_CONF_DIR}"/sites-enabled/default
+        sudo rm -rf "${NGINX_CONF_DIR}"/sites-enabled/otbr-nginx.conf
+        sudo ln -s "${NGINX_CONF_DIR}"/sites-available/otbr-nginx.conf "${NGINX_CONF_DIR}"/sites-enabled/
+
+        if have systemctl; then
+            sudo systemctl restart nginx
+        else
+            echo >&2 ' *** WARNING: systemctl not found. otbr cannot start on boot.'
+        fi
+    else
+        echo >&2 ' *** WARNING: nginx not found, please install nginx manually and run setup again'
+    fi
+}
